sidebar menu
AGH-Narzedzia-Informatyczne-2023-2024/nonogram-solver-webapp pull request #5
Opened 2023-11-18 21:12 UTC by qualv13

sidebar menu with dropdown element

2023-11-18 21:15 UTC, qualv13 commented
what do you think

2023-11-18 21:56 UTC, Frendzlu requested changes
Additional info: Component structure should look like so
```svelte
<script lang="ts">
    //imports
    //declarations
    //functions
    //standalone code
</script>
<main>
    <!-- component html structure goes here -->
</main>
<style>
     .sample {
         margin: 0 auto;   
     }
</style> 
```

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +    <link rel="stylesheet" href="style.css">
By definition, index.html should not be changed. The way Svelte works, it renders the contents of the app tree (starting from a specified file, currently `App.svelte`) by injecting it via `main.ts`

All changes are to be moved to `./src/lib/Sidebar`, and a `<Sidebar>` component should be added in `App.svelte`

2023-11-18 21:56 UTC, Frendzlu commented on style.css
> +body {
`style.css` should be moved into the `Sidebar.svelte` component

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +      <button class="dropdown-btn">Dropdown
Change anything not requiring a class (singular instance of name) to id
Remember to change `getElementsByClassName()` to `getElementById()`

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +    <div class="sidenav">
Sidenav should be collapsible. To do so, you could add a `<button id="toggleSidebar">` with appropriate css (`display: fixed`, use `top`, `left` to position), and make it change the visibility of the entire `sidenav`

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +      var dropdown = document.getElementsByClassName("dropdown-btn");
use `let` instead of `var`, just in case

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +      var i;
Remove: see below

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +      for (i = 0; i < dropdown.length; i++) {
for loops in js/ts should be written like this
```ts
for (let i = 0; i < dropdown.length; i++) {
     //...
}
```
```

2023-11-18 21:56 UTC, Frendzlu commented on index.html
> +        dropdownContent.style.display = "none";
bad formatting, please fix indentation

2023-11-19 13:26 UTC, qualv13 commented on index.html
> +      <button class="dropdown-btn">Dropdown
done

2023-11-19 13:52 UTC, Frendzlu approved these changes
lgtm

2023-11-19 13:53 UTC, merged